### ISSUE TITLE
What is the issue in here?

### ISSUE THREAD

**Issue by sudipbash** [Sankalpa-Acharya/Portfolio#1]
whatever issues with the css...

**Comment by Sankalpa-Acharya** [comment]
Site is not Properly Responsive

**Comment by sudipbash** [comment]
example?

**Comment by Sankalpa-Acharya** [comment]
once zoom 110%

**Comment by sudipbash** [comment]
is it not responsive with tablet?

**Comment by sudipbash** [comment]
> once zoom 110%

sure

**Comment by sudipbash** [comment]
![image](https://user-images.githubusercontent.com/84096206/189375085-3e9bfc62-efb9-4f2f-b8b9-ea46535e934e.png)

**Comment by Sankalpa-Acharya** [comment]
not only in mobile and in some laptop screen

> is it not responsive with tablet?

**Comment by sudipbash** [comment]
did you do css on your own?

**Comment by Sankalpa-Acharya** [comment]
> did you do css on your own?

yes

**Comment by sudipbash** [comment]
> > did you do css on your own?
> 
> yes

okay

**Comment by sudipbash** [comment]
i will take an overview and come back to you.😉

**Comment by Sankalpa-Acharya** [comment]
> i will take an overview and come back to you.😉

Ok !

**Comment by sudipbash** [comment]
there seems to be quite an interesting thing in the code..

**Comment by sudipbash** [comment]
why display none to nav ul in mobiles?

**Comment by sudipbash** [comment]
don't you want videos and projects in mobile as well?

**Comment by Sankalpa-Acharya** [comment]
> why display none to nav ul in mobiles?

Beacuse I  Don't want to display Video and Projects in Mobile

**Comment by sudipbash** [comment]
okay

**Comment by sudipbash** [comment]
then what is the issue with?
is it with your photo and the label beneath it?

**Comment by sudipbash** [comment]
![image](https://user-images.githubusercontent.com/84096206/189377783-4a2a0518-3de4-4877-a1af-3f7a65f6204b.png)

**Comment by Sankalpa-Acharya** [comment]
> okay



> then what is the issue with? is it with your photo and the label beneath it?

Buttons and Image

**Comment by sudipbash** [comment]
> ![image](https://user-images.githubusercontent.com/84096206/189377783-4a2a0518-3de4-4877-a1af-3f7a65f6204b.png)

what about this text?

**Comment by Sankalpa-Acharya** [comment]
May be I should add media query for all devices , now it is only for 750px

**Comment by sudipbash** [comment]
okay no problem, will come soon with the code.

**Comment by Sankalpa-Acharya** [comment]
![sank](https://user-images.githubusercontent.com/79009768/189379102-c09e4e3c-8b28-4660-b85a-c2e6f49a57f1.png)

Once check this as well

**Comment by sudipbash** [comment]
fixed CSS is pushed bro in the remote!

**Comment by sudipbash** [comment]
can you take a look.

**Comment by sudipbash** [comment]
issue is fixed.

**Comment by Sankalpa-Acharya** [comment]
> issue is fixed.

Yeah , everything is working fine Thank you :)
